### ISSUE TITLE
General use of scrape_urls(_

### ISSUE THREAD

**Issue by clukewatson** [liserman/archiveRetriever#4]
Hello, 

I am a novice web-scraper. My question maybe infeasible, so I will briefly describe my goal. I am attempting to get content from bank websites for scholarly research. Specifically, I wish to copy the text of the front-pages of many different webpages over time. I am getting stuck at the `scrape_urls()` step. 

Can you provide a more general use case for `scrape_urls()` that could be used for many different websites? Specifically, I do not know how to adapt the Path argument for websites other than the example. This is likely based on my lack of knowledge. 

Thank you, 
Luke

**Comment by liserman** [comment]
Hi Luke,
unfortunately, there is no easy way to scrape information from different websites effectively. Since every website has a different setup, the information you need very likely needs its own xpath for each website. If you want to learn more on webscraping and how to find the correct xpath I can recommend you the following ressources: https://www.zyte.com/blog/an-introduction-to-xpath-with-examples/,  https://www.opencodez.com/how-to-guide/how-to-use-xpath-for-web-scraping-with-r.htm. 
Best of luck with your project :)
